### ISSUE TITLE
Run emulator from docker?

### ISSUE THREAD

**Issue by chadbr** [ert78gb/google-datastore-emulator#11]
I'd like to be able to run the emulator from a mounted docker image...

Would you accept a PR for that?

I was planning to simply extend the options and modify the spawn command:

```
            self._emulator = spawn('gcloud', params, { shell: true });
```
to something like

```
            self._emulator = spawn('docker', params, { shell: true });
```

and modify _getCommandParameters to prepend the rest of the docker command
```
docker run --name gcloud-config google/cloud-sdk gcloud 
```

Thoughts?

**Comment by chadbr** [comment]
by the way - we need this for CI/CD where we simply mount the SDK to be able to access the deploy commands, etc. in a hosted VM / container.

```
#Install gcloud
docker pull google/cloud-sdk
```

**Comment by ert78gb** [comment]
Hi,

thx the idea. I thought about it, but i didn't have time to create.
If your create a PR a review, test and merge it.

pls create a new option property useDocker. Default value = false

I think use https://www.npmjs.com/package/node-docker-api is better solution then spawn new child process, but it's up to you.

pls don't forget the tests

Thx Robi

**Comment by ert78gb** [comment]
@chadbr Do you working on it? I will have a few free time on the next week and I could develop this feature is you do not started yet.

**Comment by chadbr** [comment]
Sorry - no, I haven't had time yet... it's that time in our project where everything is going at once :)

I'll let you know if I fork it before next week. We could collaborate -- or feel free to go ahead, of course 👍

**Comment by chadbr** [comment]
@ert78gb 🥇 
thanks for doing this -- trying it out today.

**Comment by chadbr** [comment]
amazeballs...

All I did was add useDocker... 💯 

    const options = {
      legacy: false, // if you need legacy support
      useDocker: true // if you need docker image
    };

**Comment by chadbr** [comment]
ok - I spoke too soon -- I was using the older version.

Could you push the latest to npm? @ert78gb

**Comment by ert78gb** [comment]
I published 1.1.0 the version number

**Comment by ert78gb** [comment]
@chadbr 
Had you time to test the docker version?

**Comment by chadbr** [comment]
Róbert, @ert78gb 
Sorry I haven't been able to get back to this until now  --
I haven't had any luck using the docker option -- 

I get these errors when I try to use it:
```
     Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint adoring_jennings (535b15
c7b129bf194ceadc63df185e106a14efb654d2611275dc47fd70880dd5): Bind for 0.0.0.0:8081 failed: port is already allocated
      at node_modules/docker-modem/lib/modem.js:239:17
      at getCause (node_modules/docker-modem/lib/modem.js:269:7)
      at Modem.buildPayload (node_modules/docker-modem/lib/modem.js:238:5)
      at IncomingMessage.<anonymous> (node_modules/docker-modem/lib/modem.js:214:14)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

I'm running on mac osx

All I did in the config is turn on useDocker:
```
    const options = {
      debug: false, // if you like to see the emulator output
      legacy: false, // if you need legacy support
      useDocker: true // if you need docker image
    };
```
I have the cloud-sdk downloaded:
```
Chadbr$ docker images
REPOSITORY                                                     TAG                 IMAGE ID            CREATED             SIZE
google/cloud-sdk                                               latest              cf92c81464fb        4 weeks ago         1.17 GB
```


anything else I can do to help debug?

**Comment by chadbr** [comment]
friendly ping? @ert78gb

**Comment by ert78gb** [comment]
sry I am very busy on this week. It is working on my machine (mac) do u use 8081 port?
Bind for 0.0.0.0:8081 failed: port is already allocated -> the error message

**Comment by chadbr** [comment]
no sweat -- yes, using 8081 (actually, not using anything - just the default...)

**Comment by ert78gb** [comment]
@chadbr Try to set port when you init the emulator
`
let options = {
      debug: true,
      host: 'localhost',
      port: 8555,
      useDocker: true
    };

    let emulator = new Emulator(options);
`

**Comment by chadbr** [comment]
that certainly helps -- but now I'm getting an issue with the latest google/cloud-sdk not including the datastore emulator :/

I guess it's a regression of this one -- https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/42

**Comment by chadbr** [comment]
yes - seems to be a new issue -- so close!!! :)

https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/74

**Comment by ert78gb** [comment]
I hope Google install all beta component in the alpine image or give a startup (command line/ ENV) option to automatically install when image start.
I think I will create a new startup option the docker image tag.

**Comment by chadbr** [comment]
@ert78gb this one looks like it will take -- could I make the image an option?

**Comment by chadbr** [comment]
oh! I missed your comment -- yes - sounds like a good option.

**Comment by ert78gb** [comment]
I created a new issue #16 I will do it tomorrow

**Comment by chadbr** [comment]
some more info ...

They seem to have reverted the sdk images back -- but I'm still having an issue...

I'm guessing the image tag options will happen - but I thought I'd pass this on just in case it was interesting...

We run our build scripts in vsts -- and in one of the steps we download the sdk (for deployment commands...)

```
docker pull google/cloud-sdk
```
This happens right away because the base images are already there, etc...

When I go to run my unit tests -- the docker options seems to be downloading the 'slim' version (and it's timing out -- which is a different problem -- I can pre-download the slim version before the unit test run)

I'm curious why the library is trying to download google/cloud-sdk:159.0.0-slim instead of using the already available google/cloud-sdk?

Here'a the log from the run:
```
2017-06-21T19:39:34.8975370Z { status: 'Pulling from google/cloud-sdk', id: '159.0.0-slim' }
2017-06-21T19:39:34.9008920Z { status: 'Already exists',
2017-06-21T19:39:34.9041430Z   progressDetail: {},
2017-06-21T19:39:34.9074660Z   id: '9f0706ba7422' }
2017-06-21T19:39:34.9107320Z { status: 'Pulling fs layer',
2017-06-21T19:39:34.9139430Z   progressDetail: {},
2017-06-21T19:39:34.9172030Z   id: '4d7b3c514173' }
```

Thanks again -- Chad

**Comment by chadbr** [comment]
one more...

the tests in my deployment pipeline are hanging when trying to use the emulator through docker.

I'm using this config:

```
    const options = {
      debug: true,
      host: 'localhost',
      port: 8555,
      useDocker: true
    };
```

but this is in the log:

```
Executing: /usr/lib/google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host=datastore-emulator --port=8081 --store_on_disk=False --consistency=0.9 --allow_remote_shutdown /root/.config/gcloud/emulators/datastore
```

So I'm guessing locally that the docker image isn't actually being used... and the build pipeline doesn't have the gcloud sdk installed so it's just hanging?

Sound right or am I on the wrong track? I'll try to debug it locally this evening and see if I can confirm my suspicions.

**Comment by ert78gb** [comment]
I will check it, but when I tested the docker solution the the emulator used docker.
I will modify the travis config and I will setup 2 build pipe 1 for local sdk and 1 for docker.
