### ISSUE TITLE
Get the output when the emulator start fails?

### ISSUE THREAD

**Issue by chadbr** [ert78gb/google-datastore-emulator#14]
Hello --

I'm running the emulator fine via docker locally... but when I try to run it on my CI server all I get is '127' errors trying to start the emulator.

Is there any way to get the output of the error displayed to the console before it fails out?

I've been trying - but not getting anywhere fast :)

Thanks -- Chad

**Comment by chadbr** [comment]
oh - I C:

    _writeDebug(message) {
        if (!this._options.debug)
            return;

        console.log(message);
    }

I'll give that a go - should have been obvious from your docs... sorry for the noise.

**Comment by Oloompa** [comment]
@chadbr Hey ! I ran in same issue and i don't understand your last message. How did you fix error 127 ?

**Comment by chadbr** [comment]
There is a debug flag on the options object you pass in... set it to true and you should see all the details in the log.
