### ISSUE TITLE
stop can't be followed by start

### ISSUE THREAD

**Issue by chrisjensen** [ert78gb/google-datastore-emulator#26]
The following code throws an exception on the restart

```
async function runTests() {
  const dse = new DatastoreEmulator();
  await dse.start();

  // do some tests

  await dse.stop();
  await dse.start();
}
```

`Error: Datastore emulator is already running.`

A brief glance at the code looks like the state is not cleared after calling `stop()`, causing the second call to `start()` to fail

**Comment by ert78gb** [comment]
thx good catch. The fix landed in 2.0.1
