### ISSUE TITLE
Should this be updated to be projectId

### ISSUE THREAD

**Issue by eggsy84** [ert78gb/google-datastore-emulator#34]
https://github.com/ert78gb/google-datastore-emulator/blob/4a9cde8da4b136d2a021a81d058949dfeed335d5/src/base-emulator.js#L140

In reference to README - it mentions the `projectId` config option, this line however seems to reference just `project` - should one of them (README or code) be updated?

**Comment by ert78gb** [comment]
Thank you for the correction. I modified the doc  because it is not causing any breaking changes.

**Comment by eggsy84** [comment]
Good stuff - no problem.

Also noticed its referenced as `projectId` in the typescript `Options` interface.

Forgive my inexperience on Typescript, wasn't sure whether that was an issue as well

**Comment by ert78gb** [comment]
thx. landed in 2.1.1
