### ISSUE TITLE
Add support for @google-cloud/datastore v4

### ISSUE THREAD

**Issue by janisto** [ert78gb/google-datastore-emulator#40]
See https://github.com/googleapis/nodejs-datastore/blob/master/CHANGELOG.md

**Comment by ert78gb** [comment]
I wanted to add, but https://github.com/googleapis/nodejs-datastore/issues/421

**Comment by ert78gb** [comment]
I am very busy in June and I don't have time to investigate what is the problem in v4

**Comment by ert78gb** [comment]
I added the v4 support but it may be breaking the unit tests.
