### ISSUE TITLE
process.exit is required to be synchronous?

### ISSUE THREAD

**Issue by chadbr** [ert78gb/google-datastore-emulator#6]
This is a great util -- thanks!

I've read in a few places that responses to this event should be synchronous -- 
```
        process.on('exit', () => {
            self.stop();
        });
```

but the stop function returns a promise...

Any thoughts? 

The stop will work fine from a testing harness... but I think I'm seeing that if the process exits, the stop leaves node processes hanging in ram.

**Comment by ert78gb** [comment]
You are absolutely right.

But the whole shutdown process is async.
I changed the exit handler in the wrapper and the most of cases will help but if someone will call process.exit() without emulator.stop() the child process will hang

**Comment by chadbr** [comment]
Thanks much.  Chad
